chore: Formatting for frontend
dasch-swiss/dsp-meta pull request #160
Opened 2024-07-30 07:33 UTC by seakayone

- **build(deps): bump log from 0.4.21 to 0.4.22 (#151)**
- **chore: Add codeowners (#153)**
- **build(deps): bump hyper from 1.2.0 to 1.4.1 (#149)**
- **build(deps): bump tracing-test from 0.2.4 to 0.2.5 (#150)**
- **feat: Add robots.txt and sitemap.xml (DEV-3931) (#152)**
- **chore: release 2.0.0 (#154)**
- **build(deps): bump ws from 7.5.9 to 7.5.10 in /web-frontend (#140)**
- **build(deps): bump braces from 3.0.2 to 3.0.3 in /web-frontend (#147)**
- **chore: Release 2.0.0 (#155)**
- **chore: disable codecov annotations (#156)**
- **chore: In schema make job title and affiliation optional for person (DEV-3933) (#157)**
- **Add prettier formatting**

2024-07-30 11:53 UTC, mpro7 requested changes
Prettier is most common and widely used formatter, which we most probably will use too, however it is not about installing and running it only, but also about turning on or off some of the options. In this PR HTML looks less readable than before ans there were added trailing slashes to the tags where they should't be. So I would vote for closing this PR. I will open one when will be ready with something to propose.

2024-07-31 08:48 UTC, mpro7 commented
"Unfortunately" all goes around Prettier, which I personally dislike. There is ESLINT which could be installed as plugin too, but under the hood it also uses Prettier. Rome. which was working well with Svelte is not maintained anymore and its successor Biome doesn't fully support Svelte. This means we kind od need to stick with Prettier, which IMO needs to be adjusted in terms of setting.
At the end it's JUST formatting :)

2024-07-31 08:49 UTC, mpro7 approved these changes

2024-07-31 09:40 UTC, seakayone commented
> "Unfortunately" all goes around Prettier, which I personally dislike. There is ESLINT which could be installed as plugin too, but under the hood it also uses Prettier. Rome. which was working well with Svelte is not maintained anymore and its successor Biome doesn't fully support Svelte. This means we kind od need to stick with Prettier, which IMO needs to be adjusted in terms of setting. At the end it's JUST formatting :)

I appreciate your feedback and the thorough research you have done, thank you. 

Despite your personal "disliked" I do not see a strong argument against using prettier as the other alternatives seem worse and prettier -at least to me - feels like the def-facto standard for JS projects. Let's merge this as a baseline formatter and then make incremental improvements on its configuration.

You are right, ESLint is often used in conjunction with prettier. AFAIU ESLint is a linter which statically analyses the source code but is not a formatter. The combination of both is also the setup in dsp-das. Do you think we should followup on this?

2024-07-31 14:10 UTC, merged